import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  reactStrictMode: true,
  // Keep `next dev` and `next build` artifacts isolated. Reusing `.next`
  // between the two modes can leave the dev server requiring vendor chunks
  // generated by a different compilation.
  distDir: process.env.NODE_ENV === "development" ? ".next-dev" : ".next",
  outputFileTracingExcludes: {
    "*": [
      "./AppDev/**/*",
      "./archive/**/*",
      "./VAULT/**/*",
      "./.claude/data/**/*",
    ],
  },
};

export default nextConfig;
